extends: google
env:
    node: true
    es6: true
parserOptions:
    sourceType: module
rules:
    max-len:
        - 2
        - code: 160
          ignoreUrls: true
    new-cap:
        - 0
    require-jsdoc: #TODO: enable this after fixing affected codes
        - 0
    eqeqeq:
        - 2
        - smart
    no-lonely-if:
        - 2
    no-trailing-spaces:
        - 2
    no-unneeded-ternary:
        - 2
    no-whitespace-before-property:
        - 2
    object-curly-spacing:
        - 2
    one-var-declaration-per-line:
        - 2
    sort-vars:
        - 2
    space-before-function-paren:
        - 2
        - never
    space-in-parens:
        - 2
    indent:
        - 2
        - 2
    no-invalid-this: #TODO: enable this after fixing affected codes
        - 0
